In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [2]:
A = np.array([[1,1,2],[-1,3,1],[0,5,2]])
print(A)

[[ 1  1  2]
 [-1  3  1]
 [ 0  5  2]]


In [3]:
E1 = np.array([[1,0,3],[0,1,0],[0,0,1]])
print(E1)

[[1 0 3]
 [0 1 0]
 [0 0 1]]


In [4]:
E1 @ A

array([[ 1, 16,  8],
       [-1,  3,  1],
       [ 0,  5,  2]])

In [5]:
E2 = np.array([[1,0,0],[0,-2,0],[0,0,1]])
print(E2)

[[ 1  0  0]
 [ 0 -2  0]
 [ 0  0  1]]


In [6]:
E2 @ A

array([[ 1,  1,  2],
       [ 2, -6, -2],
       [ 0,  5,  2]])

In [7]:
E3 = np.array([[1,0,0],[0,0,1],[0,1,0]])
print(E3)

[[1 0 0]
 [0 0 1]
 [0 1 0]]


In [8]:
E3 @ A

array([[ 1,  1,  2],
       [ 0,  5,  2],
       [-1,  3,  1]])

In [9]:
def add_row(A,k,i,j):
    """Soma k vezes a linha j à linha i na matriz A."""
    n = A.shape[0]
    E = np.eye(n)
    if i == j:
        E[i,i] = k + 1
    else:
        E[i,j] = k
    return E @ A

In [10]:
M = np.array([[1,1],[3,2]])
print(M)

[[1 1]
 [3 2]]


In [11]:
add_row(M,2,0,1)

array([[7., 5.],
       [3., 2.]])

In [12]:
add_row(M,3,1,1)

array([[ 1.,  1.],
       [12.,  8.]])

In [13]:
def scale_row(A,k,i):
    """Multiplica a linha i por k na matriz A."""
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = k
    return E @ A

In [14]:
M = np.array([[3,1],[-2,7]])
print(M)

[[ 3  1]
 [-2  7]]


In [15]:
scale_row(M,3,1)

array([[ 3.,  1.],
       [-6., 21.]])

In [16]:
A = np.array([[1,1,1],[1,-1,0]])
print(A)

[[ 1  1  1]
 [ 1 -1  0]]


In [17]:
scale_row(A,5,1)

array([[ 1.,  1.,  1.],
       [ 5., -5.,  0.]])

In [18]:
def switch_rows(A,i,j):
    """Troca as linhas i e j na matriz A."""
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = 0
    E[j,j] = 0
    E[i,j] = 1
    E[j,i] = 1
    return E @ A

In [19]:
A = np.array([[1,1,1],[1,-1,0]])
print(A)

[[ 1  1  1]
 [ 1 -1  0]]


In [20]:
switch_rows(A,0,1)

array([[ 1., -1.,  0.],
       [ 1.,  1.,  1.]])

In [21]:
M = np.array([[5,4,2],[-1,2,1],[1,1,1]])
print(M)

[[ 5  4  2]
 [-1  2  1]
 [ 1  1  1]]


In [22]:
A = np.hstack([M,np.eye(3)])
print(A)

[[ 5.  4.  2.  1.  0.  0.]
 [-1.  2.  1.  0.  1.  0.]
 [ 1.  1.  1.  0.  0.  1.]]


In [23]:
A1 = switch_rows(A,0,2)
print(A1)

[[ 1.  1.  1.  0.  0.  1.]
 [-1.  2.  1.  0.  1.  0.]
 [ 5.  4.  2.  1.  0.  0.]]


In [24]:
A2 = add_row(A1,1,1,0)
print(A2)

[[1. 1. 1. 0. 0. 1.]
 [0. 3. 2. 0. 1. 1.]
 [5. 4. 2. 1. 0. 0.]]


In [25]:
A3 = add_row(A2,-5,2,0)
print(A3)

[[ 1.  1.  1.  0.  0.  1.]
 [ 0.  3.  2.  0.  1.  1.]
 [ 0. -1. -3.  1.  0. -5.]]


In [26]:
A4 = switch_rows(A3,1,2)
print(A4)

[[ 1.  1.  1.  0.  0.  1.]
 [ 0. -1. -3.  1.  0. -5.]
 [ 0.  3.  2.  0.  1.  1.]]


In [27]:
A5 = scale_row(A4,-1,1)
print(A5)

[[ 1.  1.  1.  0.  0.  1.]
 [ 0.  1.  3. -1.  0.  5.]
 [ 0.  3.  2.  0.  1.  1.]]


In [28]:
A6 = add_row(A5,-3,2,1)
print(A6)

[[  1.   1.   1.   0.   0.   1.]
 [  0.   1.   3.  -1.   0.   5.]
 [  0.   0.  -7.   3.   1. -14.]]


In [29]:
A7 = scale_row(A6,-1/7,2)
print(A7)

[[ 1.          1.          1.          0.          0.          1.        ]
 [ 0.          1.          3.         -1.          0.          5.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


In [30]:
A8 = add_row(A7,-3,1,2)
print(A8)

[[ 1.          1.          1.          0.          0.          1.        ]
 [ 0.          1.          0.          0.28571429  0.42857143 -1.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


In [31]:
A9 = add_row(A8,-1,0,2)
print(A9)

[[ 1.          1.          0.          0.42857143  0.14285714 -1.        ]
 [ 0.          1.          0.          0.28571429  0.42857143 -1.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


In [32]:
A10 = add_row(A9,-1,0,1)
print(A10)

[[ 1.          0.          0.          0.14285714 -0.28571429  0.        ]
 [ 0.          1.          0.          0.28571429  0.42857143 -1.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


In [33]:
Minv = A10[:,3:]
print(Minv)

[[ 0.14285714 -0.28571429  0.        ]
 [ 0.28571429  0.42857143 -1.        ]
 [-0.42857143 -0.14285714  2.        ]]


In [34]:
result = Minv @ M
print(result)

[[ 1.00000000e+00  2.22044605e-16  1.11022302e-16]
 [-4.44089210e-16  1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [35]:
np.round(result,15)

array([[ 1.,  0.,  0.],
       [-0.,  1., -0.],
       [ 0.,  0.,  1.]])

In [36]:
A = np.array([[6,15,1],[8,7,12],[2,7,8]])
print(A)

[[ 6 15  1]
 [ 8  7 12]
 [ 2  7  8]]


In [37]:
b = np.array([[2],[14],[10]])
print(b)

[[ 2]
 [14]
 [10]]


In [38]:
M = np.hstack([A,b])
print(M)

[[ 6 15  1  2]
 [ 8  7 12 14]
 [ 2  7  8 10]]


In [39]:
M1 = scale_row(M,1/6,0)
print(M1)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 8.          7.         12.         14.        ]
 [ 2.          7.          8.         10.        ]]


In [40]:
M2 = add_row(M1,-8,1,0)
print(M2)

[[  1.           2.5          0.16666667   0.33333333]
 [  0.         -13.          10.66666667  11.33333333]
 [  2.           7.           8.          10.        ]]


In [41]:
M3 = add_row(M2,-2,2,0)
print(M3)

[[  1.           2.5          0.16666667   0.33333333]
 [  0.         -13.          10.66666667  11.33333333]
 [  0.           2.           7.66666667   9.33333333]]


In [42]:
M4 = scale_row(M3,-1/13,1)
print(M4)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          2.          7.66666667  9.33333333]]


In [43]:
M5 = add_row(M4,-2,2,1)
print(M5)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          0.          9.30769231 11.07692308]]


In [44]:
M6 = scale_row(M5,1/M5[2,2],2)
print(M6)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          0.          1.          1.19008264]]


In [45]:
M7 = add_row(M6,-M6[1,2],1,2)
print(M7)

[[1.         2.5        0.16666667 0.33333333]
 [0.         1.         0.         0.1046832 ]
 [0.         0.         1.         1.19008264]]


In [46]:
M8 = add_row(M7,-M7[0,2],0,2)
print(M8)

[[1.         2.5        0.         0.13498623]
 [0.         1.         0.         0.1046832 ]
 [0.         0.         1.         1.19008264]]


In [47]:
M9 = add_row(M8,-M8[0,1],0,1)
print(M9)

[[ 1.          0.          0.         -0.12672176]
 [ 0.          1.          0.          0.1046832 ]
 [ 0.          0.          1.          1.19008264]]


In [48]:
x = M9[:,3].reshape(3,1)
print(x)

[[-0.12672176]
 [ 0.1046832 ]
 [ 1.19008264]]


In [49]:
x = la.solve(A,b)
print(x)

[[-0.12672176]
 [ 0.1046832 ]
 [ 1.19008264]]


In [50]:
A = np.array([[1,1],[1,-1]])
print(A)

[[ 1  1]
 [ 1 -1]]


In [51]:
b1 = np.array([2,0])
print(b1)

[2 0]


In [52]:
x1 = la.solve(A,b1)
print(x1)

[1. 1.]


In [53]:
A = np.array([[1,1],[1,-1]])
b2 = np.array([2,0]).reshape(2,1)
x2 = la.solve(A,b2)
print(x2)

[[1.]
 [1.]]


In [54]:
A = np.array([[1,1],[1,-1]])
B = np.array([[2,2],[0,1]])
X = la.solve(A,B)
print(X)

[[1.  1.5]
 [1.  0.5]]


In [55]:
Ainv = la.solve(A,np.eye(2))
print(Ainv)
print(Ainv @ A)

[[ 0.5  0.5]
 [ 0.5 -0.5]]
[[1. 0.]
 [0. 1.]]


In [56]:
A = np.array([[2,1],[1,1]])
print(A)

[[2 1]
 [1 1]]


In [57]:
b = np.array([1,-1]).reshape(2,1)
print(b)

[[ 1]
 [-1]]


In [58]:
x = la.solve(A,b)
print(x)

[[ 2.]
 [-3.]]


In [59]:
Ainv = la.inv(A)
print(Ainv)

[[ 1. -1.]
 [-1.  2.]]


In [60]:
x = Ainv @ b
print(x)

[[ 2.]
 [-3.]]


In [61]:
N = 1000
A = np.random.rand(N,N)
b = np.random.rand(N,1)

In [62]:
A[:3,:3]

array([[0.03287234, 0.18579735, 0.95029539],
       [0.86923739, 0.50572277, 0.56221862],
       [0.11893198, 0.92175796, 0.07347836]])

In [63]:
b[:4,:]

array([[0.07799017],
       [0.98115845],
       [0.58117382],
       [0.45112237]])

In [64]:
%%timeit
x = la.solve(A,b)

The slowest run took 56.69 times longer than the fastest. This could mean that an intermediate result is being cached.
243 ms ± 257 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [65]:
%%timeit
x = la.inv(A) @ b

30.7 ms ± 4.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
