# NumPy

[NumPy](http://www.numpy.org/) é o principal pacote Python para computação numérica. As principais características do NumPy são:

* Objeto de array $N$-dimensional `ndarray`
* Operações e funções vetorizadas que se aplicam a arrays inteiros para computação rápida (broadcast)

Para começar com o NumPy, vamos adotar a convenção padrão e importá-lo usando o nome `np`:

In [1]:
import numpy as np

## Arrays NumPy

O objeto fundamental fornecido pelo pacote NumPy é o `ndarray`. Podemos pensar em um `ndarray` 1D (unidimensional) como uma lista, um `ndarray` 2D (bidimensional) como uma matriz, um `ndarray` 3D (tridimensional) como um tensor de ordem 3 (ou um "cubo" de números), e assim por diante. Veja o [tutorial do NumPy](https://docs.scipy.org/doc/numpy/user/quickstart.html) para mais informações sobre arrays NumPy.


### Criando Arrays

A função `numpy.array` cria um array NumPy a partir de uma sequência Python, como uma lista, uma tupla ou uma lista de listas. Por exemplo, crie um array NumPy 1D a partir de uma lista Python:

In [2]:
a = np.array([1,2,3,4,5])
print(a)
a

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

Note que quando imprimimos um array NumPy, ele se parece muito com uma lista Python, exceto que as entradas são separadas por espaços, enquanto as entradas em uma lista Python são separadas por vírgulas:

In [3]:
print([1,2,3,4,5])

[1, 2, 3, 4, 5]


Note também que um array NumPy é exibido de forma ligeiramente diferente quando é a saída de uma célula (em oposição a ser explicitamente impresso na saída pela função `print`):

In [4]:
a

array([1, 2, 3, 4, 5])

Use a função embutida `type` para verificar o tipo:

In [5]:
type(a)

numpy.ndarray

Crie um array NumPy 2D a partir de uma lista de listas Python:

In [6]:
M = np.array([[1,2,3],[4,5,6]])
print(M)

[[1 2 3]
 [4 5 6]]


In [7]:
type(M)

numpy.ndarray

In [8]:
M

array([[1, 2, 3],
       [4, 5, 6]])

Crie um array NumPy $n$-dimensional a partir de listas Python aninhadas. Por exemplo, o seguinte é um array NumPy 3D:

In [9]:
N = np.array([ [[1,2],[3,4]] , [[5,6],[7,8]] , [[9,10],[11,12]] ])
print(N)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


Existem várias funções NumPy para [criar arrays](https://docs.scipy.org/doc/numpy/user/quickstart.html#array-creation):

| Função | Descrição |
| ---: | :--- |
| `numpy.array(a)` | Cria um array NumPy n-dimensional a partir da sequência `a` |
| `numpy.linspace(a,b,N)` | Cria um array NumPy 1D com `N` valores igualmente espaçados de `a` a `b` (inclusivo)|
| `numpy.arange(a,b,step)` | Cria um array NumPy 1D com valores de `a` a `b` (exclusive) incrementados por `step`|
| `numpy.zeros(N)` | Cria um array NumPy 1D de zeros de comprimento $N$ |
| `numpy.zeros((n,m))` | Cria um array NumPy 2D de zeros com $n$ linhas e $m$ colunas |
| `numpy.ones(N)` | Cria um array NumPy 1D de uns de comprimento $N$ |
| `numpy.ones((n,m))` | Cria um array NumPy 2D de uns com $n$ linhas e $m$ colunas |
| `numpy.eye(N)` | Cria um array NumPy 2D com $N$ linhas e $N$ colunas com uns na diagonal (ou seja, a matriz identidade de tamanho $N$) |

Crie um array NumPy 1D com 11 valores igualmente espaçados de 0 a 1:

In [10]:
x = np.linspace(0,1,11)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


Crie um array NumPy 1D com valores de 0 a 20 (exclusive) incrementados por 2.5:

In [11]:
x2 = np.arange(0,1,0.1)
print(x2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [12]:
y = np.arange(0,20.1,2.5)
print(y)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20. ]


Estas são as funções que usaremos com mais frequência ao criar arrays NumPy. A função `numpy.linspace` funciona melhor quando sabemos o *número de pontos* que queremos no array, e `numpy.arange` funciona melhor quando sabemos o *tamanho do passo* entre os valores no array.

Crie um array NumPy 1D de zeros de comprimento 5:

In [13]:
z = np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


Crie um array NumPy 2D de zeros com 2 linhas e 5 colunas:

In [14]:
M = np.zeros((2,5))
print(M)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Crie um array NumPy 1D de uns de comprimento 7:

In [15]:
w = np.ones(7)
print(w)

[1. 1. 1. 1. 1. 1. 1.]


Crie um array NumPy 2D de uns com 3 linhas e 2 colunas:

In [16]:
N = np.ones((3,2))
print(N)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


Crie a matriz identidade de tamanho 10:

In [17]:
I = np.eye(10)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


### Tipo de Dado do Array (Datatype)

Arrays NumPy são *homogêneos*: todas as entradas no array são do mesmo tipo de dado. Trabalharemos apenas com arrays numéricos e nossos arrays conterão inteiros, floats, números complexos ou booleanos. Existem diferentes tipos de dados fornecidos pelo NumPy para diferentes aplicações, mas trabalharemos principalmente com o tipo inteiro padrão `numpy.int64` e o tipo float padrão `numpy.float64`. Eles são muito semelhantes aos tipos de dados embutidos do Python `int` e `float`, mas com algumas diferenças que não abordaremos. Confira a documentação do NumPy sobre [tipos de dados numéricos](https://docs.scipy.org/doc/numpy/user/basics.types.html) para mais informações.

O ponto mais importante por agora é saber como determinar se um array NumPy contém elementos inteiros ou flutuantes. Podemos acessar o tipo de dado de um array NumPy por seu atributo `.dtype`. Por exemplo, crie um array NumPy 2D a partir de uma lista de listas de inteiros:

In [18]:
A = np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


Esperamos que o tipo de dado de `A` seja de inteiros e verificamos:

In [19]:
type(A)

numpy.ndarray

In [20]:
A.dtype

dtype('int64')

A maioria das outras funções do NumPy que criam arrays usam o tipo de dado `numpy.float64` por padrão. Por exemplo, usando `numpy.linspace`:

In [21]:
u = np.linspace(0,1,5)
print(u)

[0.   0.25 0.5  0.75 1.  ]


In [22]:
u.dtype

dtype('float64')

In [23]:
u = np.linspace(0,5,6)
print(u)

[0. 1. 2. 3. 4. 5.]


In [24]:
u.dtype

dtype('float64')

Note que os números são impressos com um ponto decimal quando o tipo de dado do array NumPy é de qualquer tipo float.

### Dimensão, Forma (Shape) e Tamanho (Size)

Podemos pensar em um array NumPy 1D como uma lista de números, um array NumPy 2D como uma matriz, um array NumPy 3D como um cubo de números, e assim por diante. Dado um array NumPy, podemos descobrir quantas dimensões ele tem acessando seu atributo `.ndim`. O resultado é um número que nos diz quantas dimensões ele tem.

Por exemplo, crie um array NumPy 2D:

In [25]:
A = np.array([[1,2],[3,4],[5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [26]:
A.dtype

dtype('int64')

In [27]:
A.ndim

2

O resultado nos diz que `A` tem 2 dimensões. A primeira dimensão corresponde à direção vertical, contando as linhas, e a segunda dimensão corresponde à direção horizontal, contando as colunas.

Podemos descobrir quantas linhas e colunas `A` tem acessando seu atributo `.shape`:

In [28]:
A.shape

(3, 2)

O resultado é uma tupla `(3,2)` de comprimento 2, o que significa que `A` é um array 2D com 3 linhas e 2 colunas.

Também podemos descobrir quantas entradas `A` tem no total acessando seu atributo `.size`:

In [29]:
A.size

6

Este é o resultado esperado, já que sabemos que `A` tem 3 linhas e 2 colunas e, portanto, 2(3) = 6 entradas no total.

Crie um array NumPy 1D e inspecione sua dimensão, forma e tamanho:

In [30]:
r = np.array([9,3,1,7])
print(r)

[9 3 1 7]


In [31]:
r.ndim

1

In [32]:
r.shape

(4,)

In [33]:
r.size

4

A variável `r` é atribuída a um array NumPy 1D de comprimento 4. Note que `r.shape` é uma tupla com uma única entrada `(4,)`.

### Fatiamento e Indexação (Slicing and Indexing)

Acessar as entradas em um array é chamado de *indexação* e acessar linhas e colunas (ou subarrays) é chamado de *fatiamento*. Veja a documentação do NumPy para mais informações sobre [indexação e fatiamento](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

Crie um array NumPy 1D:

In [34]:
v = np.linspace(0,5,11)
print(v)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


Acesse as entradas em um array 1D usando a notação de colchetes, assim como em uma lista Python. Por exemplo, acesse a entrada no índice 3:

In [35]:
v[3]

np.float64(1.5)

In [36]:
print(v[0])

0.0


In [37]:
v

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

Note que os índices de arrays NumPy começam em 0, assim como as sequências Python.

Crie um array 2D de inteiros:

In [38]:
B = np.array([[6, 5, 3, 1, 1],[1, 0, 4, 0, 1],[5, 9, 2, 2, 9]])
print(B)

[[6 5 3 1 1]
 [1 0 4 0 1]
 [5 9 2 2 9]]


Acesse as entradas em um array 2D usando colchetes com 2 índices. Em particular, acesse a entrada no índice de linha 1 e no índice de coluna 2:

In [39]:
B[1,2]

np.int64(4)

In [40]:
type(B)

numpy.ndarray

In [41]:
B.dtype

dtype('int64')

Acesse a entrada superior esquerda do array:

In [42]:
B[0,0]

np.int64(6)

Índices negativos funcionam para arrays NumPy como funcionam para sequências Python. Acesse a entrada inferior direita do array:

In [43]:
B[-1,-1]

np.int64(9)

Acesse a linha no índice 2 usando a sintaxe de dois pontos `:`:

In [44]:
linha=B[2,:]
print(linha)

[5 9 2 2 9]


In [45]:
linha.shape

(5,)

In [46]:
B[2]

array([5, 9, 2, 2, 9])

Acesse a coluna no índice 3:

In [47]:
coluna=B[:,3]

In [48]:
coluna.shape

(3,)

Selecione o subarray das linhas nos índices 1 e 2, e das colunas nos índices 2, 3 e 4:

In [49]:
print(B)

[[6 5 3 1 1]
 [1 0 4 0 1]
 [5 9 2 2 9]]


In [50]:
subB = B[1:3,2:5]
print(subB)

[[4 0 1]
 [2 2 9]]


(note que ele não inclui os extremos (3,5))

In [51]:
subB2 = B[1:10,2:4]
print(subB2)

[[4 0]
 [2 2]]


Fatias de arrays NumPy são novamente arrays NumPy, mas possivelmente de uma dimensão diferente:

In [52]:
subB.ndim

2

In [53]:
subB.shape

(2, 3)

In [54]:
subB2.shape

(2, 2)

In [55]:
type(subB)

numpy.ndarray

A variável `subB` é atribuída a um array NumPy 2D de forma 2 por 3.

Vamos fazer o mesmo para a coluna no índice 2:

In [56]:
print(B)

[[6 5 3 1 1]
 [1 0 4 0 1]
 [5 9 2 2 9]]


In [57]:
colB = B[:,2]
print(colB)

[3 4 2]


In [58]:
colB.ndim

1

In [59]:
colB.shape

(3,)

In [60]:
type(colB)

numpy.ndarray

A variável `colB` é atribuída a um array NumPy 1D de comprimento 3.

### Empilhamento (Stacking)

Podemos construir arrays maiores a partir de arrays menores, [empilhando-os](https://docs.scipy.org/doc/numpy/user/quickstart.html#stacking-together-different-arrays) ao longo de diferentes dimensões, usando as funções `numpy.hstack` e `numpy.vstack`.

Empilhe 3 arrays NumPy 1D diferentes de comprimento 3 verticalmente, formando uma matriz 3 por 3:

In [61]:
x = np.array([1,1,1])
y = np.array([2,2,2])
z = np.array([3,3,3])
vstacked = np.vstack((x,y,z))
print(vstacked)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


Empilhe arrays NumPy 1D horizontalmente para criar outro array 1D:

In [62]:
hstacked = np.hstack((x,y,z))
print(hstacked)

[1 1 1 2 2 2 3 3 3]


Use `numpy.hstack` e `numpy.vstack` para construir a matriz $T$ onde

$$
T =
\begin{bmatrix}
1 & 1 & 2 & 2 \\
1 & 1 & 2 & 2 \\
3 & 3 & 4 & 4 \\
3 & 3 & 4 & 4
\end{bmatrix}
$$

In [63]:
A = np.ones((2,2))
B = 2*A
C = 3*A
D = 4*A
A_B = np.hstack((A,B))
print(A_B)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]]


In [64]:
C_D = np.hstack((C,D))
print(C_D)

[[3. 3. 4. 4.]
 [3. 3. 4. 4.]]


In [65]:
T = np.vstack((A_B,C_D))
print(T)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


  ### Cópias versus Visões (Views),

Uma característica extremamente importante do NumPy, e que difere das listas do Python, é que o fatiamento (`slicing`) de um array **não cria uma cópia** dos dados. Em vez disso, ele cria uma **visão** (`view`) dos dados originais. Isso significa que a nova variável do tipo array está simplesmente olhando para os mesmos dados que o array original.

Isso é feito por razões de performance: ao trabalhar com arrays muito grandes, criar cópias de todos os dados seria ineficiente em termos de memória e tempo. No entanto, é crucial saber que, **se você modificar uma visão, o array original também será modificado**.

Uma **cópia** (`copy`), por outro lado, é um novo array, com seus próprios dados duplicados do original. Modificar uma cópia **não** afeta o array original.

Vamos começar com um exemplo que demonstra uma visão (`view`)

In [66]:
a = np.arange(0,11,1) # Cria um array original: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print('Array original a:', a)

# Criamos uma visão de 'a' pegando uma fatia
b_visao = a[0:5]
print('Visão b:', b_visao)

Array original a: [ 0  1  2  3  4  5  6  7  8  9 10]
Visão b: [0 1 2 3 4]


Agora, vamos modificar o primeiro elemento da visão `b_visao` e ver o que acontece com o array original `a`:

In [67]:
b_visao[0] = 99
print('Visão b modificada:', b_visao)
print('Array original a DEPOIS da modificação em b:', a)

Visão b modificada: [99  1  2  3  4]
Array original a DEPOIS da modificação em b: [99  1  2  3  4  5  6  7  8  9 10]


In [68]:
a[0]=100
print('Visão b modificada DEPOIS da modificação em a:', b_visao)

Visão b modificada DEPOIS da modificação em a: [100   1   2   3   4]


Como você pode ver, a modificação em `b_visao` também alterou o array original `a`! Isso ocorre porque `b_visao` é uma **visão** dos dados de `a`, não uma cópia.

Para evitar esse comportamento e ter um array completamente independente, você deve criar uma **cópia** explícita usando o método `.copy()`.

In [69]:
a = np.arange(10)
print('Array original a:', a)

# Criamos uma cópia explícita de 'a'
c_copia = a[0:5].copy()
print('Cópia c:', c_copia)

Array original a: [0 1 2 3 4 5 6 7 8 9]
Cópia c: [0 1 2 3 4]


Agora, se modificarmos a cópia, o original permanecerá inalterado:

In [70]:
c_copia[0] = 99
print('Cópia c modificada:', c_copia)
print('Array original a DEPOIS da modificação em c:', a)

Cópia c modificada: [99  1  2  3  4]
Array original a DEPOIS da modificação em c: [0 1 2 3 4 5 6 7 8 9]


In [71]:
a[0]=100
print('Cópia c modificada DEPOIS da modificação em a:', c_copia)

Cópia c modificada DEPOIS da modificação em a: [99  1  2  3  4]


Resumo Rápido:

* **Visão (View):**
     * Criada por fatiamento (`slicing`).
     * Não possui seus próprios dados; compartilha os dados do array original.
     * Modificações na visão **afetam** o array original.
     * Rápida e eficiente em termos de memória.
     
* **Cópia (Copy):**
     * Criada explicitamente com o método `.copy()`.
     * Possui sua própria cópia independente dos dados.
     * Modificações na cópia **não afetam** o array original.
     * Usa mais memória e tempo de processamento.

## Operações e Funções

### Operações com Arrays

[Operadores aritméticos](https://docs.scipy.org/doc/numpy/user/quickstart.html#basic-operations), incluindo adição `+`, subtração `-`, multiplicação `*`, divisão `/` e exponenciação `**`, são aplicados a arrays *elemento a elemento*. Para adição e subtração, estas são as operações vetoriais familiares que vemos em álgebra linear:

In [72]:
v = np.array([1,2,3])
w = np.array([1,0,-1])

In [73]:
v + w

array([2, 2, 2])

In [74]:
v - w

array([0, 2, 4])

Da mesma forma, a multiplicação e a divisão de arrays são realizadas elemento a elemento:

In [75]:
v * w

array([ 1,  0, -3])

In [76]:
w / v

array([ 1.        ,  0.        , -0.33333333])

In [77]:
divisao = v/w

/var/folders/gh/8l0f9hn57gs9zsxjfn5ykhy00000gn/T/ipykernel_94217/298847599.py:1: RuntimeWarning: divide by zero encountered in divide
  divisao = v/w


In [78]:
divisao[1]=100000
print(divisao)

[ 1.e+00  1.e+05 -3.e+00]


Note que o tipo de dado de `v` e `w` é `numpy.int64`, no entanto, a divisão `w / v` retorna um array com o tipo de dado `numpy.float64`.

O operador de exponenciação `**` também atua elemento a elemento no array:

In [79]:
v ** 2

array([1, 4, 9])

Estas operações para arrays 2D funcionam da mesma forma, elemento a elemento:

In [80]:
A = np.array([[3,1],[2,-1]])
B = np.array([[2,-2],[5,1]])
print(A)
print(B)

[[ 3  1]
 [ 2 -1]]
[[ 2 -2]
 [ 5  1]]


In [81]:
A + B

array([[ 5, -1],
       [ 7,  0]])

In [82]:
A - B

array([[ 1,  3],
       [-3, -2]])

In [83]:
A / B

array([[ 1.5, -0.5],
       [ 0.4, -1. ]])

In [84]:
A * B

array([[ 6, -2],
       [10, -1]])

In [85]:
A ** 2

array([[9, 1],
       [4, 1]])

No Python 3.5+, o símbolo `@` calcula a multiplicação de matrizes para arrays NumPy:

In [86]:
print(A)
print(B)

[[ 3  1]
 [ 2 -1]]
[[ 2 -2]
 [ 5  1]]


In [87]:
A @ B

array([[11, -5],
       [-1, -5]])

Usando a função `np.dot()`: antes do Python 3.5, esta era a maneira padrão de realizar a multiplicação de matrizes. A função `np.dot()` é mais geral e também calcula o produto escalar de vetores.

In [88]:
produto_matricial_dot = np.dot(A, B)
print("Produto matricial com np.dot(A, B):\n", produto_matricial_dot)

Produto matricial com np.dot(A, B):
 [[11 -5]
 [-1 -5]]


In [89]:
print(v)
print(w)

[1 2 3]
[ 1  0 -1]


In [90]:
np.dot(v,w)

np.int64(-2)

[Potências de matrizes](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.matrix_power.html) são calculadas pela função `numpy.linalg.matrix_power`. É um nome de função longo, então é conveniente importá-lo com um nome mais curto:

In [91]:
from numpy.linalg import matrix_power as mpow

Calcule $A^3$:

In [92]:
mpow(A,3)

array([[37,  9],
       [18,  1]])

Equivalentemente, use o operador `@` para calcular $A^3$:

In [93]:
A @ A @ A

array([[37,  9],
       [18,  1]])

### Broadcasting

Sabemos da álgebra linear que só podemos somar matrizes do mesmo tamanho. [Broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) é um conjunto de regras do NumPy que flexibiliza essa restrição e nos permite combinar um array menor com um maior quando faz sentido.

Por exemplo, suponha que queremos criar um array NumPy 1D de valores de $y$ para $x=0.0,0.25,0.5,0.75,1.0$ para a função $y = x^2 + 1$. Pelo que vimos até agora, faz sentido criar `x`, depois `x**2` e então somar um array de uns `[1. 1. 1. 1. 1.]`:

In [94]:
x = np.linspace(0,1,5)
print(x)
print(x**2)
y = x**2 + np.array([1,1,1,1,1])
print(y)

[0.   0.25 0.5  0.75 1.  ]
[0.     0.0625 0.25   0.5625 1.    ]
[1.     1.0625 1.25   1.5625 2.    ]


Um exemplo de broadcasting no NumPy é a seguinte operação equivalente:

In [95]:
y = x**2 + 1
print(y)

[1.     1.0625 1.25   1.5625 2.    ]


O número 1 é um escalar e estamos somando-o a um array NumPy 1D de comprimento 5. A regra de broadcasting neste caso é aplicar (broadcast) o valor escalar 1 em todo o array maior. O resultado é uma sintaxe mais simples para uma operação muito comum.

Vamos tentar outro exemplo. O que acontece quando tentamos somar um array NumPy 1D de comprimento 4 a um array NumPy 2D de tamanho 3 por 4?

In [96]:
u = np.array([1,2,3,4])
print(u)

[1 2 3 4]


In [97]:
A = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
print(A)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [98]:
result = A + u
print(result)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


O array NumPy 1D é aplicado (broadcast) a todo o array 2D porque o comprimento da última dimensão em cada array é igual!

Este procedimento não funciona quando a dimensão não é compatível:

In [99]:
u2=np.array([1,2])
result = A + u2
print(result)

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

### Funções de Array

Existem *muitas* [funções de array](https://docs.scipy.org/doc/numpy/reference/routines.html) que podemos usar para calcular com arrays NumPy. A seguir está uma lista parcial e veremos mais de perto as funções matemáticas na próxima seção.

| | | |
| :---: | :---: | :---: |
| `numpy.sum` | `numpy.prod` | `numpy.mean` |
| `numpy.max` | `numpy.min` | `numpy.std` |
| `numpy.argmax` | `numpy.argmin` | `numpy.var` |

Crie um array NumPy 1D com valores aleatórios e calcule:

In [ ]:
arr = np.array([8,-2,4,7,-3])
print(arr)

In [ ]:
print(np.prod(arr))
8*(-2)*4*7*(-3)

Calcule a média dos valores no array:

In [ ]:
np.mean(arr)

Verifique a média mais uma vez:

In [ ]:
m = np.sum(arr) / arr.size
print(m)

In [ ]:
print(np.std(arr))
print(np.var(arr))
print(np.std(arr)**2)

In [ ]:
arr2 = 2.8*np.ones(5)
print(arr2)
print(np.std(arr2))

Encontre o índice do elemento máximo no array:

In [ ]:
print(arr)

In [ ]:
max_i = np.argmax(arr)
print(max_i)

Verifique o valor máximo no array:

In [ ]:
np.max(arr)

In [ ]:
arr[max_i]

Funções de array também se aplicam a arrays 2D (e arrays $N$-dimensionais em geral) com o recurso adicional de que podemos escolher aplicar funções de array ao array inteiro, pelas colunas ou pelas linhas (ou qualquer eixo).

Crie um array NumPy 2D com valores aleatórios e calcule a soma de todas as entradas:

In [ ]:
M = np.array([[2,4,2],[2,1,1],[3,2,0],[0,6,2]])
print(M)

In [ ]:
np.sum(M)

A função `numpy.sum` também aceita um argumento de palavra-chave `axis` que determina ao longo de qual dimensão calcular a soma:

In [ ]:
np.sum(M,axis=0) # Soma das colunas

In [ ]:
np.sum(M,axis=1) # Soma das linhas

### Funções Matemáticas

As [funções matemáticas](http://docs.scipy.org/doc/numpy/reference/routines.math.html) no NumPy são chamadas de [funções universais](https://docs.scipy.org/doc/numpy/user/quickstart.html#universal-functions) e são *vetorizadas*. Funções vetorizadas operam *elemento a elemento* em arrays, produzindo arrays como saída, e são construídas para calcular valores em arrays *muito* rapidamente. A seguir, uma lista parcial de funções matemáticas:

| | | |
| :---: | :---: | :---: |
| `numpy.sin` | `numpy.cos` | `numpy.tan` |
| `numpy.exp` | `numpy.log` | `numpy.log10` |
| `numpy.arcsin` | `numpy.arccos` | `numpy.arctan` |

Calcule os valores de $\sin(2 \pi x)$ para $x = 0, 0.25, 0.5, 0.75, 1.0$:

In [ ]:
x = np.arange(0,1.25,0.25)
print(x)

In [ ]:
np.sin(2*np.pi*x)

Esperamos o array `[0. 1. 0. -1. 0.]`, no entanto, há (como sempre com números de ponto flutuante) alguns erros de arredondamento no resultado. Em computação numérica, podemos interpretar um número como $10^{-16}$ como $0$.

Calcule os valores de $\log_{10}(x)$ para $x = 1,10,100,1000,10000$:

In [ ]:
x = np.array([1,10,100,1000,10000])
print(x)

In [ ]:
np.log10(x)

Note que também podemos avaliar funções matemáticas com valores escalares:

In [ ]:
np.sin(0)

In [ ]:
np.sin(np.pi)

O NumPy também fornece constantes matemáticas familiares, como $\pi$ e $e$:

In [ ]:
np.pi

In [ ]:
np.e

Por exemplo, verifique o limite

$$
\lim_{x \to \infty} \arctan(x) = \frac{\pi}{2}
$$

avaliando $\arctan(x)$ para algum valor grande (arbitrário) de $x$:

In [ ]:
np.arctan(100000)

In [ ]:
np.pi/2

## Geradores de Números Aleatórios

O subpacote `numpy.random` contém funções para gerar arrays NumPy de [números aleatórios](https://docs.scipy.org/doc/numpy/reference/routines.random.html) amostrados de diferentes distribuições. A seguir, uma lista parcial de distribuições:

| Função | Descrição |
| :--- | :--- |
| `numpy.random.rand(d1,...,dn)` | Cria um array NumPy (com forma `(d1,...,dn)`) com entradas amostradas uniformemente de `[0,1)` |
| `numpy.random.randn(d1,...,dn)` | Cria um array NumPy (com forma `(d1,...,dn)`) com entradas amostradas da distribuição normal padrão (média 0 e desvio padrão 1)|
| `numpy.random.randint(a,b,size)` | Cria um array NumPy (com forma `size`) com entradas inteiras de 'low' (inclusivo) a 'high' (exclusive) |

Amostre um número aleatório da [distribuição uniforme](https://en.wikipedia.org/wiki/Uniform_distribution_%28continuous%29):

In [ ]:
np.random.rand()

Amostre 3 números aleatórios:

In [ ]:
np.random.rand(3)

Crie um array NumPy 2D de amostras aleatórias:

In [ ]:
np.random.rand(2,4)

Amostras aleatórias da [distribuição normal padrão](https://en.wikipedia.org/wiki/Normal_distribution) (média 0 e variância 1):

In [ ]:
np.random.randn()

In [ ]:
np.random.randn(3)

In [ ]:
numeros = np.random.randn(3000)
print(numeros[1:10])

In [ ]:
print(np.mean(numeros))
print(np.std(numeros))

In [ ]:
np.random.randn(3,1)

Inteiros aleatórios amostrados uniformemente de vários intervalos:

In [ ]:
np.random.randint(-10,10)

In [ ]:
np.random.randint(0,2,(4,8))

In [ ]:
np.random.randint(-9,10,(5,2))

Geradores de números pseudoaleatórios são algoritmos que produzem sequências de números aparentemente aleatórios, mas que, na verdade, são determinados por um valor inicial chamado "semente".

Ao conduzir experimentos, especialmente em áreas como aprendizado de máquina ou simulações, a reprodutibilidade é crucial. Ao estabelecer uma base, os pesquisadores podem garantir que seus resultados sejam consistentes e possam ser replicados por outros ou por eles próprios posteriormente.

A função `numpy.random.seed()` é usada para definir a semente para o gerador de números pseudoaleatórios. Essa função garante que a sequência de números "aleatórios" gerada pelo NumPy será a mesma sempre que o código for executado com o mesmo valor de semente.

Quando np.random.seed(valor) é chamado, ele inicializa esse algoritmo com o valor fornecido. Chamadas subsequentes às funções de geração de números aleatórios do NumPy produzirão uma sequência previsível com base nessa semente inicial.

In [ ]:
np.random.seed(2)
print(np.random.randint(-5,6,(3,2)))
print(np.random.randint(-5,6,(3,2)))

In [ ]:
print(np.random.randint(-5,6,(3,2)))

## Exemplos

### Otimização por Força Bruta

Encontre os valores de [máximo e mínimo absolutos](https://en.wikipedia.org/wiki/Maxima_and_minima) da função

$$
f(x) = x\sin(x)+\cos(4x)
$$

no intervalo $[0,2\pi]$. Sabemos que os valores máximo e mínimo devem ocorrer nas extremidades $x=0,2\pi$ ou em pontos críticos onde $f'(x)=0$. No entanto, a derivada é dada por

$$
f'(x) = \sin(x) + x \cos(x) - 4\sin(4x)
$$

e a equação $f'(x) = 0$ é impossível de resolver explicitamente.

Em vez disso, crie um array NumPy 1D de valores de $x$ de $0$ a $2\pi$ de comprimento $N$ (para algum valor arbitrariamente grande de $N$) e use as funções `numpy.min` e `numpy.max` para encontrar os valores máximo e mínimo de $y$, e as funções `numpy.argmin` e `numpy.argmax` para encontrar os índices dos valores de $x$ correspondentes.

In [ ]:
N = 20000
x = np.linspace(0,2*np.pi,N)
y = x * np.sin(x) + np.cos(4*x)
y_max = np.max(y)
y_min = np.min(y)
x_max = x[np.argmax(y)]
x_min = x[np.argmin(y)]
print('Absolute maximum value is y =',y_max,'at x =',x_max)
print('Absolute minimum value is y =',y_min,'at x =',x_min)

In [ ]:
y[np.argmax(y)]

### Somas de Riemann

Escreva uma função chamada `exp_int` que receba os parâmetros de entrada $b$ e $N$ e retorne a [soma de Riemann](https://en.wikipedia.org/wiki/Riemann_sum) à esquerda

$$
\int_0^b e^{-x^2} dx \approx \sum_{k=0}^{N-1} e^{-x_k^2} \Delta x
$$

para $\Delta x = b/N$ e a partição $x_k=k \, \Delta x$, $k=0,\dots,N$.

In [ ]:
def exp_int(b,N):
    "Compute left Riemann sum of exp(-x^2) from 0 to b with N subintervals."
    x = np.linspace(0,b,N+1)
    x_left_endpoints = x[:-1]
    Delta_x = b/N
    I = Delta_x * np.sum(np.exp(-x_left_endpoints**2))
    return I

A integral imprópria satisfaz a [bela identidade](https://en.wikipedia.org/wiki/Gaussian_integral)

$$
\int_0^{\infty} e^{-x^2} dx = \frac{\sqrt{\pi}}{2}
$$

Calcule a integral com valores grandes de $b$ e $N$:

In [ ]:
exp_int(100,100000)

Podemos melhorar este método simplesmente trocando o ponto à esquerda em cada subintervalo pelo ponto médio:

In [ ]:
def exp_int_mid(b,N):
    "Compute mid Riemann sum of exp(-x^2) from 0 to b with N subintervals."
    x = np.linspace(0,b,N+1)
    Delta_x = b/N
    x_midpoints = x[:-1]+Delta_x/2
    I = Delta_x * np.sum(np.exp(-x_midpoints**2))
    return I

In [ ]:
exp_int_mid(100,100000)

Compare com o valor verdadeiro:

In [ ]:
np.pi**0.5/2

### Produtos Infinitos

A função cosseno tem a seguinte representação de produto infinito

$$
\cos x = \prod_{k = 1}^{\infty} \left(1 - \frac{4 x^2}{\pi^2 (2k - 1)^2} \right)
$$

Escreva uma função chamada `cos_product` que receba os parâmetros de entrada $x$ e $N$ e retorne o $N$-ésimo produto parcial

$$
\prod_{k = 1}^{N} \left(1 - \frac{4 x^2}{\pi^2 (2k - 1)^2} \right)
$$

In [ ]:
def cos_product(x,N):
    "Compute the product prod_{k=1}^N (1 - 4x^2/(pi^2 (2k - 1)^2)."
    k = np.arange(1,N+1)
    #print(k)
    terms = 1 - 4*x**2 / (np.pi**2 * (2*k - 1)**2)
    #print(terms)
    return np.prod(terms)

Verifique nossa função usando valores cujo resultado conhecemos. Por exemplo, $\cos(0)=1$, $\cos(\pi)=-1$ e $\cos(\pi/4) = \frac{1}{\sqrt{2}}$.

In [ ]:
cos_product(np.pi/3,100)

In [ ]:
cos_product(np.pi,10000)

In [ ]:
cos_product(np.pi/4,10000000)

In [ ]:
1/2**0.5

# Exercícios



**Exercício 1.** O logaritmo natural satisfaz a seguinte integral definida

$$
\int_1^e \frac{\ln x \ dx}{(1 + \ln x)^2} = \frac{e}{2} - 1
$$

Escreva uma função chamada `log_integral` que receba os parâmetros de entrada $c$ e $N$ e retorne o valor da soma de Riemann (à direita)

$$
\int_1^c \frac{\ln x \ dx}{(1 + \ln x)^2} \approx \sum_{k=1}^N \frac{\ln x_k \ \Delta x}{(1 + \ln x_k)^2} \ , \ \ \Delta x = \frac{c - 1}{N}
$$

para a partição $x_k = 1 + k \Delta x$, para $k = 0, \dots , N$.

**Exercício 2.** Escreva uma função chamada `k_sum` que receba os parâmetros de entrada `k` e `N` e retorne a soma parcial

$$
\sum_{n=1}^{N} \frac{1}{n^k}
$$

Verifique sua função comparando com a identidade da série infinita

$$
\sum_{n=1}^{\infty} \frac{(-1)^{n+1}}{n^2} = \frac{\pi^2}{12}
$$

**Exercício 3.** Escreva uma função chamada `dot` que receba 3 entradas `M`, `i` e `j`, onde `M` é um array NumPy quadrado, e a função retorna o produto escalar da $i$-ésima linha e da $j$-ésima coluna de $M$.

**Exercício 4.** Escreva uma função chamada `aproxima_pi` que usa o método de Monte Carlo para estimar o valor de $\pi$. A função deve receber um parâmetro `N` (o número de pontos a serem gerados).

**Lógica do Método de Monte Carlo:**
1.  Imagine um quadrado de lado 2, centrado na origem (coordenadas de -1 a 1).
2.  Dentro deste quadrado, há um círculo de raio 1, também centrado na origem.
3.  A área do quadrado é $(2)^2 = 4$. A área do círculo é $\pi r^2 = \pi (1)^2 = \pi$.
4.  A razão entre a área do círculo e a área do quadrado é $\pi / 4$.
5.  Se você gerar `N` pontos aleatórios uniformemente dentro do quadrado, a proporção de pontos que caem *dentro* do círculo deve ser aproximadamente igual à razão das áreas ($\pi / 4$).
6.  Um ponto $(x, y)$ está dentro do círculo se $x^2 + y^2 < 1$.

**Dicas:**
* Use `np.random.rand(N, 2)` para gerar `N` pares de coordenadas (x, y) entre 0 e 1. Depois, ajuste-os para o intervalo [-1, 1].
* Aproveite as operações vetorizadas do NumPy para verificar a condição $x^2 + y^2 < 1$ para todos os pontos de uma só vez.
* A função `np.sum()` em um array booleano conta o número de valores `True`.

**Exercício 5.** Escreva uma função chamada `normalizar_colunas` que recebe uma matriz (array NumPy 2D) `M` e a padroniza. Padronizar significa subtrair a média e dividir pelo desvio padrão de **cada coluna**. O resultado deve ser uma nova matriz onde cada coluna tem média 0 e desvio padrão 1.

**Fórmula de Padronização (escore-z) para um valor x em uma amostra:**
$$z = \frac{x - \mu}{\sigma}$$
Onde $\mu$ é a média da amostra e $\sigma$ é o desvio padrão.

**Dicas:**
* Use `np.mean(M, axis=0)` e `np.std(M, axis=0)` para calcular a média e o desvio padrão de cada coluna.
* Aproveite o *broadcasting* do NumPy para subtrair o vetor de médias e dividir pelo vetor de desvios padrão da matriz original `M`.

**Exercício 6.** Implemente o **Crivo de Eratóstenes** usando NumPy para encontrar todos os números primos até um número `N`. Escreva uma função `crivo_numpy(N)` que retorne um array com os primos.

**Lógica do Algoritmo:**
1.  Crie um array booleano `is_prime` de tamanho `N+1` e inicialize todos os valores como `True`.
2.  Marque os índices 0 e 1 como `False`, pois não são primos.
3.  Comece com o primeiro primo, `p = 2`.
4.  Enquanto `p * p <= N`:
    * Se `is_prime[p]` ainda for `True`, então `p` é um primo.
    * Marque todos os múltiplos de `p` (começando de `p*p` até `N`, com passo `p`) como `False`. Por exemplo, para `p=2`, marque 4, 6, 8, ... como `False`. Para `p=3`, marque 9, 12, 15, ... como `False`.
    * Vá para o próximo número.
5.  No final, os índices `i` onde `is_prime[i]` é `True` correspondem aos números primos.

**Dicas:**
* A beleza desta implementação com NumPy está em usar fatiamento (`slicing`) com passo para marcar os múltiplos. Por exemplo: `is_prime[p*p : N+1 : p] = False`.
* Para obter o resultado final, use `np.where(is_prime)` ou indexação booleana.

**Exercício 7.** Simule um **passeio aleatório (random walk)** em 1D. Escreva uma função `passeio_aleatorio(passos)` que simule um caminho de `passos` etapas e retorne um array com a posição em cada etapa.

**Lógica do Passeio Aleatório:**
1.  Comece na posição 0.
2.  Para cada etapa, o movimento pode ser +1 ou -1, com igual probabilidade.
3.  A posição em qualquer etapa `t` é a soma de todos os movimentos feitos até aquele momento.

**Dicas:**
* Gere um array com `passos` números aleatórios, por exemplo, 0 ou 1, usando `np.random.randint()`.
* Mapeie esses valores para -1 e 1. Uma forma de fazer isso é: `2 * array - 1`.
* A função `np.cumsum()` é perfeita para calcular a soma cumulativa dos passos e obter o caminho.

**Exercício 8.** Uma imagem em tons de cinza pode ser representada como uma matriz 2D. Uma imagem colorida (RGB) pode ser representada como um array 3D de forma `(altura, largura, 3)`, onde a última dimensão representa os canais de cor Vermelho, Verde e Azul.

Escreva uma função `converter_para_cinza(imagem_rgb)` que receba um array NumPy 3D (simulando uma imagem RGB) e o converta para um array 2D (tons de cinza).

**Fórmula de Luminosidade para Conversão:**
$$Cinza = 0.299 \times Vermelho + 0.587 \times Verde + 0.114 \times Azul$$

**Dicas:**
* Crie um array aleatório de inteiros entre 0 e 255 com forma `(100, 200, 3)` para simular uma imagem de 100x200 pixels.
* Use o fatiamento (`slicing`) do NumPy para acessar cada canal de cor (ex: `imagem_rgb[:, :, 0]` para o canal vermelho).
* Use a fórmula para combinar os canais em um único array 2D.