In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

In [2]:
A = np.array([[1,0],[0,-2]])
print(A)

[[ 1  0]
 [ 0 -2]]


In [3]:
results = la.eig(A)

In [4]:
print(results[0])

[ 1.+0.j -2.+0.j]


In [5]:
print(results[1])

[[1. 0.]
 [0. 1.]]


In [6]:
eigvals, eigvecs = la.eig(A)
print(eigvals)

[ 1.+0.j -2.+0.j]


In [7]:
print(eigvecs)

[[1. 0.]
 [0. 1.]]


In [8]:
eigvals = eigvals.real
print(eigvals)

[ 1. -2.]


In [9]:
lambda1 = eigvals[1]
print(lambda1)

-2.0


In [10]:
v1 = eigvecs[:,1].reshape(2,1)
print(v1)

[[0.]
 [1.]]


In [11]:
A @ v1

array([[ 0.],
       [-2.]])

In [12]:
lambda1 * v1

array([[-0.],
       [-2.]])

In [13]:
n = 4
P = np.random.randint(0,10,(n,n))
print(P)

[[3 7 6 2]
 [4 7 1 0]
 [7 4 2 9]
 [8 6 5 8]]


In [14]:
S = P @ P.T
print(S)

[[ 98  67  79 112]
 [ 67  66  58  79]
 [ 79  58 150 162]
 [112  79 162 189]]


In [15]:
evals, evecs = la.eig(S)
print(evals)

[432.54179711+0.j  56.10541196+0.j  13.64845826+0.j   0.70433266+0.j]


In [16]:
evals = evals.real
print(evals)

[432.54179711  56.10541196  13.64845826   0.70433266]


In [17]:
print(evecs)

[[ 0.41158241  0.59674264  0.5839518  -0.36537438]
 [ 0.30439544  0.56517134 -0.76559157  0.04235948]
 [ 0.5539979  -0.54039837 -0.2116873  -0.59686214]
 [ 0.65652849 -0.18013656  0.16750622  0.71306579]]


In [18]:
v1 = evecs[:,0] # A primeira coluna é o primeiro autovetor
print(v1)

[0.41158241 0.30439544 0.5539979  0.65652849]


In [19]:
v2 = evecs[:,1] # A segunda coluna é o segundo autovetor
print(v2)

[ 0.59674264  0.56517134 -0.54039837 -0.18013656]


In [20]:
v1 @ v2

np.float64(-4.163336342344337e-17)

In [21]:
P = np.array([[1,1],[1,-1]])
print(P)

[[ 1  1]
 [ 1 -1]]


In [22]:
D = np.diag((3,1))
print(D)

[[3 0]
 [0 1]]


In [23]:
M = P @ D @ la.inv(P)
print(M)

[[2. 1.]
 [1. 2.]]


In [24]:
evals, evecs = la.eig(M)
print(evals)

[3.+0.j 1.+0.j]


In [25]:
print(evecs)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [26]:
Pinv = la.inv(P)

In [27]:
k = 20

In [28]:
%%timeit
result = M.copy()
for _ in range(1,k):
    result = result @ M

14.5 µs ± 260 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [29]:
%%timeit
P @ D**k @ Pinv

2.44 µs ± 144 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
