# Sistemas Lineares

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

## Sistemas Lineares

Um [sistema de equações lineares](https://en.wikipedia.org/wiki/System_of_linear_equations) é um conjunto de equações lineares

\begin{align}
a_{0,0}x_0 + a_{0,1}x_2 + \cdots + a_{0,n}x_n & = b_0 \\\
a_{1,0}x_0 + a_{1,1}x_2 + \cdots + a_{1,n}x_n & = b_1 \\\
& \vdots \\\
a_{m,0}x_0 + a_{m,1}x_2 + \cdots + a_{m,n}x_n & = b_m \\\
\end{align}

Em notação matricial, um sistema linear é $A \mathbf{x}= \mathbf{b}$, onde

$$
A = \begin{bmatrix}
a_{0,0} & a_{0,1} & \cdots & a_{0,n} \\\
a_{1,0} & a_{1,1} & \cdots & a_{1,n} \\\
\vdots & & & \vdots \\\
a_{m,0} & a_{m,1} & \cdots & a_{m,n} \\\
\end{bmatrix}
 \ \ , \ \
\mathbf{x} = \begin{bmatrix}
x_0 \\\ x_1 \\\ \vdots \\\ x_n
\end{bmatrix}
 \ \ , \ \
\mathbf{b} = \begin{bmatrix}
b_0 \\\ b_1 \\\ \vdots \\\ b_m
\end{bmatrix}
$$

## Eliminação Gaussiana

O procedimento geral para resolver um sistema de equações lineares é chamado de [eliminação gaussiana](https://en.wikipedia.org/wiki/Gaussian_elimination). A ideia é realizar operações elementares nas linhas para reduzir o sistema à sua forma escalonada e então resolvê-lo.

### Operações Elementares nas Linhas

As [operações elementares nas linhas](https://en.wikipedia.org/wiki/Elementary_matrix#Elementary_row_operations) incluem:

1. Somar $k$ vezes a linha $j$ à linha $i$.
2. Multiplicar a linha $i$ pelo escalar $k$.
3. Trocar as linhas $i$ e $j$.

Cada uma das operações elementares nas linhas é o resultado da multiplicação por uma matriz elementar (à esquerda).
Para somar $k$ vezes a linha $j$ à linha $i$ em uma matriz $A$, multiplicamos $A$ pela matriz $E$, onde $E$ é igual à matriz identidade, exceto que o elemento $i,j$ é $E_{i,j} = k$. Por exemplo, se $A$ é 3x3 e queremos somar 3 vezes a linha 2 à linha 0 (usando indexação baseada em 0), então

$$
E_1 = \begin{bmatrix}
1 & 0 & 3 \\\
0 & 1 & 0 \\\
0 & 0 & 1
\end{bmatrix}
$$

Vamos verificar o cálculo:

In [2]:
A = np.array([[1,1,2],[-1,3,1],[0,5,2]])
print(A)

[[ 1  1  2]
 [-1  3  1]
 [ 0  5  2]]


In [3]:
E1 = np.array([[1,0,3],[0,1,0],[0,0,1]])
print(E1)

[[1 0 3]
 [0 1 0]
 [0 0 1]]


In [4]:
E1 @ A

array([[ 1, 16,  8],
       [-1,  3,  1],
       [ 0,  5,  2]])

Para multiplicar a linha $i$ por $k$ em uma matriz $A$, multiplicamos $A$ pela matriz $E$, onde $E$ é igual à matriz identidade, exceto que o elemento $i,i$ é $E_{i,i} = k$. Por exemplo, se $A$ é 3x3 e queremos multiplicar a linha 1 por -2, então

$$
E_2 = \begin{bmatrix}
1 & 0 & 0 \\\
0 & -2 & 0 \\\
0 & 0 & 1
\end{bmatrix}
$$

Vamos verificar o cálculo:

In [5]:
E2 = np.array([[1,0,0],[0,-2,0],[0,0,1]])
print(E2)

[[ 1  0  0]
 [ 0 -2  0]
 [ 0  0  1]]


In [6]:
E2 @ A

array([[ 1,  1,  2],
       [ 2, -6, -2],
       [ 0,  5,  2]])

Finalmente, para trocar a linha $i$ e a linha $j$ em uma matriz $A$, multiplicamos $A$ pela matriz $E$, onde $E$ é igual à matriz identidade, exceto que $E_{i,i} = 0$, $E_{j,j} = 0$, $E_{i,j} = 1$ e $E_{j,i} = 1$. Por exemplo, se $A$ é 3x3 e queremos trocar a linha 1 e a linha 2, então

$$
E_3 = \begin{bmatrix}
1 & 0 & 0 \\\
0 & 0 & 1 \\\
0 & 1 & 0
\end{bmatrix}
$$

Vamos verificar o cálculo:

In [7]:
E3 = np.array([[1,0,0],[0,0,1],[0,1,0]])
print(E3)

[[1 0 0]
 [0 0 1]
 [0 1 0]]


In [8]:
E3 @ A

array([[ 1,  1,  2],
       [ 0,  5,  2],
       [-1,  3,  1]])

### Implementação

Vamos escrever funções para implementar as operações elementares nas linhas. Primeiramente, vamos escrever uma função chamada `add_row` que recebe os parâmetros de entrada $A$, $k$, $i$ e $j$ e retorna o array NumPy resultante de somar $k$ vezes a linha $j$ à linha $i$ na matriz $A$. Se $i=j$, vamos dizer que a função escala a linha $i$ por $k+1$, pois este seria o resultado de $k$ vezes a linha $i$ somada à linha $i$.

In [9]:
def add_row(A,k,i,j):
    """Soma k vezes a linha j à linha i na matriz A."""
    n = A.shape[0]
    E = np.eye(n)
    if i == j:
        E[i,i] = k + 1
    else:
        E[i,j] = k
    return E @ A

Vamos testar nossa função:

In [10]:
M = np.array([[1,1],[3,2]])
print(M)

[[1 1]
 [3 2]]


In [11]:
add_row(M,2,0,1)

array([[7., 5.],
       [3., 2.]])

In [12]:
add_row(M,3,1,1)

array([[ 1.,  1.],
       [12.,  8.]])

Vamos escrever uma função chamada `scale_row` que recebe 3 parâmetros de entrada $A$, $k$ e $i$ e retorna a matriz que resulta da multiplicação da linha $i$ por $k$ na matriz $A$.

In [13]:
def scale_row(A,k,i):
    """Multiplica a linha i por k na matriz A."""
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = k
    return E @ A

In [14]:
M = np.array([[3,1],[-2,7]])
print(M)

[[ 3  1]
 [-2  7]]


In [15]:
scale_row(M,3,1)

array([[ 3.,  1.],
       [-6., 21.]])

In [16]:
A = np.array([[1,1,1],[1,-1,0]])
print(A)

[[ 1  1  1]
 [ 1 -1  0]]


In [17]:
scale_row(A,5,1)

array([[ 1.,  1.,  1.],
       [ 5., -5.,  0.]])

Vamos escrever uma função chamada `switch_rows` que recebe 3 parâmetros de entrada $A$, $i$ e $j$ e retorna a matriz que resulta da troca das linhas $i$ e $j$ na matriz $A$.

In [18]:
def switch_rows(A,i,j):
    """Troca as linhas i e j na matriz A."""
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = 0
    E[j,j] = 0
    E[i,j] = 1
    E[j,i] = 1
    return E @ A

In [19]:
A = np.array([[1,1,1],[1,-1,0]])
print(A)

[[ 1  1  1]
 [ 1 -1  0]]


In [20]:
switch_rows(A,0,1)

array([[ 1., -1.,  0.],
       [ 1.,  1.,  1.]])

## Exemplos

### Encontrar a Inversa

Vamos aplicar nossas funções à matriz aumentada $[M \ | \ I]$ para encontrar a inversa da matriz $M$:

In [21]:
M = np.array([[5,4,2],[-1,2,1],[1,1,1]])
print(M)

[[ 5  4  2]
 [-1  2  1]
 [ 1  1  1]]


In [22]:
A = np.hstack([M,np.eye(3)])
print(A)

[[ 5.  4.  2.  1.  0.  0.]
 [-1.  2.  1.  0.  1.  0.]
 [ 1.  1.  1.  0.  0.  1.]]


In [23]:
A1 = switch_rows(A,0,2)
print(A1)

[[ 1.  1.  1.  0.  0.  1.]
 [-1.  2.  1.  0.  1.  0.]
 [ 5.  4.  2.  1.  0.  0.]]


In [24]:
A2 = add_row(A1,1,1,0)
print(A2)

[[1. 1. 1. 0. 0. 1.]
 [0. 3. 2. 0. 1. 1.]
 [5. 4. 2. 1. 0. 0.]]


In [25]:
A3 = add_row(A2,-5,2,0)
print(A3)

[[ 1.  1.  1.  0.  0.  1.]
 [ 0.  3.  2.  0.  1.  1.]
 [ 0. -1. -3.  1.  0. -5.]]


In [26]:
A4 = switch_rows(A3,1,2)
print(A4)

[[ 1.  1.  1.  0.  0.  1.]
 [ 0. -1. -3.  1.  0. -5.]
 [ 0.  3.  2.  0.  1.  1.]]


In [27]:
A5 = scale_row(A4,-1,1)
print(A5)

[[ 1.  1.  1.  0.  0.  1.]
 [ 0.  1.  3. -1.  0.  5.]
 [ 0.  3.  2.  0.  1.  1.]]


In [28]:
A6 = add_row(A5,-3,2,1)
print(A6)

[[  1.   1.   1.   0.   0.   1.]
 [  0.   1.   3.  -1.   0.   5.]
 [  0.   0.  -7.   3.   1. -14.]]


In [29]:
A7 = scale_row(A6,-1/7,2)
print(A7)

[[ 1.          1.          1.          0.          0.          1.        ]
 [ 0.          1.          3.         -1.          0.          5.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


In [30]:
A8 = add_row(A7,-3,1,2)
print(A8)

[[ 1.          1.          1.          0.          0.          1.        ]
 [ 0.          1.          0.          0.28571429  0.42857143 -1.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


In [31]:
A9 = add_row(A8,-1,0,2)
print(A9)

[[ 1.          1.          0.          0.42857143  0.14285714 -1.        ]
 [ 0.          1.          0.          0.28571429  0.42857143 -1.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


In [32]:
A10 = add_row(A9,-1,0,1)
print(A10)

[[ 1.          0.          0.          0.14285714 -0.28571429  0.        ]
 [ 0.          1.          0.          0.28571429  0.42857143 -1.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


Vamos verificar se encontramos a inversa $M^{-1}$ corretamente:

In [33]:
Minv = A10[:,3:]
print(Minv)

[[ 0.14285714 -0.28571429  0.        ]
 [ 0.28571429  0.42857143 -1.        ]
 [-0.42857143 -0.14285714  2.        ]]


In [34]:
result = Minv @ M
print(result)

[[ 1.00000000e+00  2.22044605e-16  1.11022302e-16]
 [-4.44089210e-16  1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


Sucesso! Podemos ver o resultado mais claramente se arredondarmos para 15 casas decimais:

In [35]:
np.round(result,15)

array([[ 1.,  0.,  0.],
       [-0.,  1., -0.],
       [ 0.,  0.,  1.]])

### Resolver um Sistema

Vamos usar nossas funções para realizar a eliminação gaussiana e resolver um sistema de equações lineares $A \mathbf{x} = \mathbf{b}$.

In [36]:
A = np.array([[6,15,1],[8,7,12],[2,7,8]])
print(A)

[[ 6 15  1]
 [ 8  7 12]
 [ 2  7  8]]


In [37]:
b = np.array([[2],[14],[10]])
print(b)

[[ 2]
 [14]
 [10]]


Forme a matriz aumentada $M$:

In [38]:
M = np.hstack([A,b])
print(M)

[[ 6 15  1  2]
 [ 8  7 12 14]
 [ 2  7  8 10]]


Realize as operações nas linhas:

In [39]:
M1 = scale_row(M,1/6,0)
print(M1)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 8.          7.         12.         14.        ]
 [ 2.          7.          8.         10.        ]]


In [40]:
M2 = add_row(M1,-8,1,0)
print(M2)

[[  1.           2.5          0.16666667   0.33333333]
 [  0.         -13.          10.66666667  11.33333333]
 [  2.           7.           8.          10.        ]]


In [41]:
M3 = add_row(M2,-2,2,0)
print(M3)

[[  1.           2.5          0.16666667   0.33333333]
 [  0.         -13.          10.66666667  11.33333333]
 [  0.           2.           7.66666667   9.33333333]]


In [42]:
M4 = scale_row(M3,-1/13,1)
print(M4)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          2.          7.66666667  9.33333333]]


In [43]:
M5 = add_row(M4,-2,2,1)
print(M5)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          0.          9.30769231 11.07692308]]


In [44]:
M6 = scale_row(M5,1/M5[2,2],2)
print(M6)

[[ 1.          2.5         0.16666667  0.33333333]
 [ 0.          1.         -0.82051282 -0.87179487]
 [ 0.          0.          1.          1.19008264]]


In [45]:
M7 = add_row(M6,-M6[1,2],1,2)
print(M7)

[[1.         2.5        0.16666667 0.33333333]
 [0.         1.         0.         0.1046832 ]
 [0.         0.         1.         1.19008264]]


In [46]:
M8 = add_row(M7,-M7[0,2],0,2)
print(M8)

[[1.         2.5        0.         0.13498623]
 [0.         1.         0.         0.1046832 ]
 [0.         0.         1.         1.19008264]]


In [47]:
M9 = add_row(M8,-M8[0,1],0,1)
print(M9)

[[ 1.          0.          0.         -0.12672176]
 [ 0.          1.          0.          0.1046832 ]
 [ 0.          0.          1.          1.19008264]]


Sucesso! A solução de $Ax=b$ é

In [48]:
x = M9[:,3].reshape(3,1)
print(x)

[[-0.12672176]
 [ 0.1046832 ]
 [ 1.19008264]]


Ou, podemos fazer do jeito fácil...

In [49]:
x = la.solve(A,b)
print(x)

[[-0.12672176]
 [ 0.1046832 ]
 [ 1.19008264]]


## `scipy.linalg.solve`

Estamos interessados principalmente em sistemas lineares $A \mathbf{x} = \mathbf{b}$ onde há uma solução única $\mathbf{x}$. Este é o caso quando $A$ é uma matriz quadrada ($m=n$) e $\mathrm{det}(A) \not= 0$. Para resolver tal sistema, podemos usar a função [`scipy.linalg.solve`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve.html).

A função retorna uma solução do sistema de equações $A \mathbf{x} = \mathbf{b}$. Por exemplo:

In [50]:
A = np.array([[1,1],[1,-1]])
print(A)

[[ 1  1]
 [ 1 -1]]


In [51]:
b1 = np.array([2,0])
print(b1)

[2 0]


E resolvemos:

In [52]:
x1 = la.solve(A,b1)
print(x1)

[1. 1.]


Note que a saída $\mathbf{x}$ é retornada como um array NumPy 1D quando o vetor $\mathbf{b}$ (o lado direito) é inserido como um array NumPy 1D. Se inserirmos $\mathbf{b}$ como um array NumPy 2D, então a saída é um array NumPy 2D. Por exemplo:

In [53]:
A = np.array([[1,1],[1,-1]])
b2 = np.array([2,0]).reshape(2,1)
x2 = la.solve(A,b2)
print(x2)

[[1.]
 [1.]]


Finalmente, se o lado direito $\mathbf{b}$ é uma matriz, então a saída é uma matriz do mesmo tamanho. É a solução de $A \mathbf{X} = \mathbf{B}$ quando $\mathbf{B}$ é uma matriz. Por exemplo:

In [54]:
A = np.array([[1,1],[1,-1]])
B = np.array([[2,2],[0,1]])
X = la.solve(A,B)
print(X)

[[1.  1.5]
 [1.  0.5]]


In [55]:
Ainv = la.solve(A,np.eye(2))
print(Ainv)
print(Ainv @ A)

[[ 0.5  0.5]
 [ 0.5 -0.5]]
[[1. 0.]
 [0. 1.]]


### Exemplo Simples

Vamos calcular a solução do sistema de equações

\begin{align}
2x + y &= 1 \\\
x + y &= -1
\end{align}

Crie a matriz de coeficientes:

In [56]:
A = np.array([[2,1],[1,1]])
print(A)

[[2 1]
 [1 1]]


E o vetor $\mathbf{b}$:

In [57]:
b = np.array([1,-1]).reshape(2,1)
print(b)

[[ 1]
 [-1]]


E resolvemos:

In [58]:
x = la.solve(A,b)
print(x)

[[ 2.]
 [-3.]]


Podemos verificar a solução calculando a inversa de $A$:

In [59]:
Ainv = la.inv(A)
print(Ainv)

[[ 1. -1.]
 [-1.  2.]]


E multiplicamos $A^{-1} \mathbf{b}$ para resolver para $\mathbf{x}$:

In [60]:
x = Ainv @ b
print(x)

[[ 2.]
 [-3.]]


Obtemos o mesmo resultado. Sucesso!

### Inversa ou Resolver

É uma má ideia usar a inversa $A^{-1}$ para resolver $A \mathbf{x} = \mathbf{b}$ se $A$ for grande. É muito caro computacionalmente. Vamos criar uma matriz aleatória grande $A$ e um vetor $\mathbf{b}$ e calcular a solução $\mathbf{x}$ de 2 maneiras:

In [61]:
N = 1000
A = np.random.rand(N,N)
b = np.random.rand(N,1)

Verifique os primeiros elementos de $A$:

In [62]:
A[:3,:3]

array([[0.37266688, 0.72029669, 0.53101879],
       [0.1252094 , 0.48393647, 0.15475272],
       [0.2392168 , 0.88049339, 0.99595982]])

E para $\mathbf{b}$:

In [63]:
b[:4,:]

array([[0.36686751],
       [0.9142607 ],
       [0.70042264],
       [0.73991561]])

Agora comparamos a velocidade de `scipy.linalg.solve` com `scipy.linalg.inv`:

In [64]:
%%timeit
x = la.solve(A,b)

The slowest run took 4.06 times longer than the fastest. This could mean that an intermediate result is being cached.
43.6 ms ± 22.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [65]:
%%timeit
x = la.inv(A) @ b

40.1 ms ± 13.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Resolver com `scipy.linalg.solve` é muito mais rápido!