In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
a = np.array([1,3,-2,1])
print(a)

[ 1  3 -2  1]


In [3]:
a.ndim

1

In [4]:
a.shape

(4,)

In [5]:
a.size

4

In [6]:
M = np.array([[1,2],[3,7],[-1,5]])
print(M)

[[ 1  2]
 [ 3  7]
 [-1  5]]


In [7]:
M.ndim

2

In [8]:
M.shape

(3, 2)

In [9]:
M.size

6

In [10]:
col = M[:,1]
print(col)

[2 7 5]


In [11]:
col.ndim

1

In [12]:
col.shape

(3,)

In [13]:
col.size

3

In [14]:
print(col)

[2 7 5]


In [15]:
column = col.reshape(3,1)
print(column)

[[2]
 [7]
 [5]]


In [16]:
print('Dimensões:', column.ndim)
print('Forma:', column.shape)
print('Tamanho:', column.size)

Dimensões: 2
Forma: (3, 1)
Tamanho: 3


In [17]:
print(col)

[2 7 5]


In [18]:
print('Dimensões:',col.ndim)
print('Forma:',col.shape)
print('Tamanho:',col.size)

Dimensões: 1
Forma: (3,)
Tamanho: 3


In [19]:
col2 = column.reshape(1,3)
print(col2)

[[2 7 5]]


In [20]:
M = np.array([[3,4],[-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


In [21]:
M * M

array([[ 9, 16],
       [ 1, 25]])

In [22]:
M @ M

array([[ 5, 32],
       [-8, 21]])

In [23]:
A = np.array([[1,3],[-1,7]])
print(A)

[[ 1  3]
 [-1  7]]


In [24]:
B = np.array([[5,2],[1,2]])
print(B)

[[5 2]
 [1 2]]


In [25]:
I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [26]:
2*I + 3*A - A@B

array([[-3.,  1.],
       [-5., 11.]])

In [27]:
from numpy.linalg import matrix_power as mpow

In [28]:
M = np.array([[3,4],[-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


In [29]:
mpow(M,2)

array([[ 5, 32],
       [-8, 21]])

In [30]:
mpow(M,5)

array([[-1525,  3236],
       [ -809,    93]])

In [31]:
M @ M @ M @ M @ M

array([[-1525,  3236],
       [ -809,    93]])

In [32]:
mpow(M,3)

array([[-17, 180],
       [-45,  73]])

In [33]:
M @ M @ M

array([[-17, 180],
       [-45,  73]])

In [34]:
print(M)

[[ 3  4]
 [-1  5]]


In [35]:
print(M.T)

[[ 3 -1]
 [ 4  5]]


In [36]:
M @ M.T

array([[25, 17],
       [17, 26]])

In [37]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [38]:
la.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [39]:
np.trace(A)

np.int64(5)

In [40]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [41]:
la.det(A)

np.float64(-2.0)

In [42]:
print(A)

[[1 2]
 [3 4]]


In [43]:
trace_A = np.trace(A)
det_A = la.det(A)
I = np.eye(2)
A @ A - trace_A * A + det_A * I

array([[0., 0.],
       [0., 0.]])

In [44]:
N = np.random.randint(0,10,[2,2])
print(N)

[[2 6]
 [7 3]]


In [45]:
trace_N = np.trace(N)
det_N = la.det(N)
I = np.eye(2)
N @ N - trace_N * N + det_N * I

array([[0., 0.],
       [0., 0.]])

In [46]:
v = np.array([1,2,3])
w = np.array([1,1,1])
print(v*w)
print(np.sum(v*w))

[1 2 3]
6


In [47]:
def proj(v,w):
    '''Projeta o vetor v em w.'''
    v = np.array(v)
    w = np.array(w)
    return np.sum(v * w)/np.sum(w * w) * w   # ou (v @ w)/(w @ w) * w

In [48]:
proj([1,2,3],[1,1,1])

array([2., 2., 2.])